In [1]:
import pandas as pd

In [5]:
## series
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series: \n", series)

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [8]:
data = [10,20,30]
index = ['a', 'b', 'c']
pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

In [17]:
## data frame 

data = {
    'Name' : ['Krish', 'Ajay', 'BintyDon'],
    'Age' : [25,30,45],
    'City' : ['NY','LA','Barca']
}

df = pd.DataFrame(data)
print(df)

       Name  Age   City
0     Krish   25     NY
1      Ajay   30     LA
2  BintyDon   45  Barca

In [18]:
##addimg age to the column
df['Age'] = df['Age']+1
df

       Name  Age   City
0     Krish   26     NY
1      Ajay   31     LA
2  BintyDon   46  Barca

In [20]:
import numpy as np
np.array(df)

array([['Krish', 26, 'NY'],
       ['Ajay', 31, 'LA'],
       ['BintyDon', 46, 'Barca']], dtype=object)

In [21]:
df = pd.read_csv('sales.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [22]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000